import { useEffect, useMemo, useState, type CSSProperties } from 'react';
import { ArrowUpRight,CheckCircle2, Clock3, Flame, Plus, Sparkles, Target, TrendingUp } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import type { Task } from '../types';
import { completeTask, getTasks } from '../services/taskService';
import Toast from '../components/Toast';

const dateLabel = (d?: string) => d ? new Date(d).toLocaleDateString([], { month: 'short', day: 'numeric' }) : 'No due date';
export default function Dashboard() {
    const [tasks, setTasks] = useState<Task[]>([]); const [loading, setLoading] = useState(true); const [toast, setToast] = useState(''); const navigate = useNavigate();
    useEffect(() => { getTasks({ limit: 100, sortBy: 'createdAt', order: 'desc' }).then(r => setTasks(r.tasks)).catch(() => { }).finally(() => setLoading(false)) }, []);
    const done = tasks.filter(t => t.status === 'completed').length; const active = tasks.filter(t => t.status !== 'completed').length; const overdue = tasks.filter(t => t.dueDate && new Date(t.dueDate) < new Date() && t.status !== 'completed').length; const rate = tasks.length ? Math.round(done / tasks.length * 100) : 0; const urgent = tasks.filter(t => t.priority === 'urgent' || t.priority === 'high').filter(t => t.status !== 'completed').slice(0, 5);
    const today = useMemo(() => tasks.filter(t => t.dueDate && new Date(t.dueDate).toDateString() === new Date().toDateString() && t.status !== 'completed').slice(0, 6), [tasks]);
    const finish = async (t: Task) => { try { const updated = await completeTask(t._id); setTasks(v => v.map(x => x._id === updated._id ? updated : x)); setToast('Nice. Task completed.') } catch (e) { setToast(e instanceof Error ? e.message : 'Unable to complete task.') } };
    return <section className="page"><div className="dashboard-intro"><div><p className="eyebrow">OVERVIEW</p><h1>Make room for what matters.</h1><p className="page-sub">Your workspace is clearer when your next move is visible.</p></div><button className="btn primary" onClick={() => navigate('/tasks?new=1')}><Plus size={18} /> New task</button></div>
        <div className="stat-grid"><div className="stat-card hero-stat"><div><span>Completion rate</span><Target className="stat-icon" size={18} /></div><strong>{rate}%</strong><small><TrendingUp size={13} />{done} completed of {tasks.length || 0}</small></div><div className="stat-card"><span>Total tasks</span><strong>{tasks.length}</strong><small>Across your workspace</small></div><div className="stat-card"><span>Active</span><strong>{active}</strong><small>Ready for focus</small></div><div className="stat-card"><span>Overdue</span><strong>{overdue}</strong><small><Flame size={13} /> Needs attention</small></div></div>
        <div className="dashboard-grid"><div className="panel"><div className="panel-head"><div><p className="eyebrow">FOCUS QUEUE</p><h3>What needs you next</h3></div><Link to="/tasks">View all <ArrowUpRight size={15} /></Link></div>{loading ? <div className="skeleton-list compact">{[1, 2, 3].map(i => <div className="task-skeleton" key={i}><i /><div><b /><span /></div></div>)}</div> : urgent.length ? <div className="task-list">{urgent.map(t => <div className="task-row" key={t._id}><button className="task-check" onClick={() => void finish(t)} aria-label="Complete task" /><div className="task-main"><strong>{t.title}</strong><span>{t.category || 'Personal'} · {dateLabel(t.dueDate)}</span></div><span className={`priority ${t.priority}`}>{t.priority}</span></div>)}</div> : <div className="empty"><Sparkles size={27} /><strong>Nothing urgent right now.</strong><span>You have space to work deliberately.</span></div>}</div>
            <div className="panel progress-panel"><div className="panel-head"><div><p className="eyebrow">YOUR RHYTHM</p><h3>Completion</h3></div><CheckCircle2 className="stat-icon" /></div><div className="ring-wrap"><div className="progress-ring" style={{ '--progress': `${rate}%` } as CSSProperties}><div><strong>{rate}%</strong><span>complete</span></div></div></div><div className="progress-caption"><span>Completed</span><strong>{done}</strong><span>Active</span><strong>{active}</strong></div></div>
        </div>
        <div className="section-heading"><div><p className="eyebrow">TODAY</p><h3>Today's tasks</h3></div><Link to="/tasks?search=">Open task list <ArrowUpRight size={15} /></Link></div>
        <div className="panel today-panel">{today.length ? <div className="task-list">{today.map(t => <div className="task-row" key={t._id}><button className="task-check" onClick={() => void finish(t)} aria-label="Complete task" /><div className="task-main"><strong>{t.title}</strong><span>{dateLabel(t.dueDate)} · {t.status === 'in-progress' ? 'In progress' : 'To do'}</span></div><span className={`priority ${t.priority}`}>{t.priority}</span></div>)}</div> : <div className="empty"><Clock3 size={27} /><strong>Your day is open.</strong><span>Add a task when the next important action becomes clear.</span><button className="btn ghost" onClick={() => navigate('/tasks?new=1')}>Add task</button></div>}</div>
        <div className="quote-strip"><span className="quote-mark">“</span><p>Consistency beats intensity. Keep the next action small enough to start.</p><span>TASKFLOW PRINCIPLE</span></div>{toast && <Toast message={toast} onClose={() => setToast('')} />}</section>
}
