import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Bell, Check, CircleUserRound, LockKeyhole, LogOut, Monitor, Moon, Palette, Shield, Sun } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';
import { changePassword, getPreferences, updatePreferences } from '../services/authService';
import type { Theme } from '../types';
import Toast from '../components/Toast';

const notifyKey='taskflow-notifications';
export default function SettingsPage(){
 const {user,saveProfile,logout}=useAuth(); const navigate=useNavigate(); const {theme,setTheme}=useTheme(); const [active,setActive]=useState<'appearance'|'account'|'notifications'|'security'>('appearance');
 const [name,setName]=useState(user?.name||''); const [saving,setSaving]=useState(false); const [toast,setToast]=useState(''); const [notifications,setNotifications]=useState(()=>localStorage.getItem(notifyKey)!=='off'); const [prefsLoading,setPrefsLoading]=useState(true);
 const [currentPassword,setCurrentPassword]=useState(''); const [newPassword,setNewPassword]=useState(''); const [confirm,setConfirm]=useState(''); const [pwBusy,setPwBusy]=useState(false); const [pwError,setPwError]=useState('');
 useEffect(()=>setName(user?.name||''),[user]);
 useEffect(()=>{let cancelled=false; getPreferences().then(p=>{if(cancelled)return;setNotifications(p.notifications);localStorage.setItem(notifyKey,p.notifications?'on':'off');}).catch(()=>{}).finally(()=>{if(!cancelled)setPrefsLoading(false)}); return()=>{cancelled=true}},[]);
 const save=async()=>{setSaving(true);try{await saveProfile({name:name.trim()});setToast('Profile updated successfully.')}catch(e){setToast(e instanceof Error?e.message:'Unable to update profile.')}finally{setSaving(false)}};
 const toggleNotifications=(v:boolean)=>{setNotifications(v);localStorage.setItem(notifyKey,v?'on':'off');void updatePreferences({notifications:v}).then(()=>setToast(v?'Notifications enabled.':'Notifications paused.')).catch(e=>setToast(e instanceof Error?e.message:'Unable to update notifications.'))};
 const passwordSave=async()=>{setPwError('');if(newPassword.length<8){setPwError('New password must be at least 8 characters.');return}if(newPassword!==confirm){setPwError('New passwords do not match.');return}setPwBusy(true);try{await changePassword({currentPassword,newPassword});setCurrentPassword('');setNewPassword('');setConfirm('');setToast('Password changed successfully.')}catch(e){setPwError(e instanceof Error?e.message:'Password change is unavailable until the backend password endpoint is enabled.')}finally{setPwBusy(false)}};
 return <section className="page"><div className="topbar"><div><p className="eyebrow">PREFERENCES</p><h1>Settings</h1><p className="page-sub">Shape the workspace around the way you work.</p></div></div>
  <div className="settings-shell"><aside className="settings-nav">{([['appearance','Appearance',Palette],['account','Account',CircleUserRound],['notifications','Notifications',Bell],['security','Security',Shield]] as const).map(([id,label,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}><Icon size={18}/><span>{label}</span></button>)}</aside>
   <div className="settings-content">
    {active==='appearance'&&<div className="settings-section"><div className="section-title"><div><p className="eyebrow">APPEARANCE</p><h2>Choose your atmosphere.</h2><p>Theme changes apply instantly and persist between sessions.</p></div></div><div className="theme-grid">{([['light','Light',Sun,'Bright, soft and focused.'],['dark','Dark',Moon,'Low contrast strain, high focus.'],['system','System',Monitor,'Follow your device preference.']] as const).map(([id,label,Icon,desc])=><button key={id} className={`theme-option ${theme===id?'selected':''}`} onClick={()=>{const next=id as Theme;setTheme(next);void updatePreferences({theme:next}).then(()=>setToast('Appearance updated.')).catch(e=>setToast(e instanceof Error?e.message:'Unable to sync appearance.'))}}><div className="theme-icon"><Icon/></div><div><strong>{label}</strong><span>{desc}</span></div>{theme===id&&<span className="theme-check"><Check size={15}/></span>}</button>)}</div></div>}
    {active==='account'&&<div className="settings-section"><div className="section-title"><div><p className="eyebrow">ACCOUNT</p><h2>Keep your profile current.</h2><p>Changes sync to your TaskFlow account when the profile endpoint is enabled.</p></div></div><div className="profile-edit"><div className="avatar large">{name?.[0]?.toUpperCase()||'T'}</div><div className="profile-fields"><label>Full name<input value={name} onChange={e=>setName(e.target.value)} maxLength={50}/></label><label>Email<input value={user?.email||''} disabled/></label><button className="btn primary" onClick={save} disabled={saving}>{saving?'Saving…':'Save profile'}</button></div></div><div className="session-card"><div><p className="eyebrow">SESSION</p><strong>Signed in as {user?.email}</strong><span>Authentication uses a secure HTTP-only cookie session.</span></div><button className="btn ghost" onClick={async()=>{await logout();navigate('/login',{replace:true})}}><LogOut size={16}/> Sign out</button></div></div>}
    {active==='notifications'&&<div className="settings-section"><div className="section-title"><div><p className="eyebrow">NOTIFICATIONS</p><h2>Stay informed, not interrupted.</h2><p>Your notification preference is stored with your account and reflected across sessions.</p></div></div><div className="setting-row"><div className="setting-icon"><Bell/></div><div className="setting-copy"><strong>TaskFlow notifications</strong><span>Show reminders and in-app feedback for task actions.</span></div><button className={`switch ${notifications?'on':''}`} disabled={prefsLoading} role="switch" aria-checked={notifications} onClick={()=>toggleNotifications(!notifications)}><i/></button></div><div className="setting-row"><div className="setting-icon"><Check/></div><div className="setting-copy"><strong>Completion feedback</strong><span>Celebrate completed tasks with subtle confirmation.</span></div><span className="status-pill">Always on</span></div></div>}
    {active==='security'&&<div className="settings-section"><div className="section-title"><div><p className="eyebrow">SECURITY</p><h2>Protect your access.</h2><p>Use a unique password and the secure session cookie provided by the API.</p></div></div><div className="security-badges"><div><LockKeyhole/><strong>HTTP-only session</strong><span>Token is not exposed to page JavaScript.</span></div><div><Shield/><strong>Protected API</strong><span>Requests are scoped to the authenticated user.</span></div></div><div className="password-form"><h3>Change password</h3><label>Current password<input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} autoComplete="current-password"/></label><label>New password<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} autoComplete="new-password" placeholder="At least 8 characters"/></label><label>Confirm new password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/></label>{pwError&&<p className="form-error">{pwError}</p>}<button className="btn primary" disabled={pwBusy||!currentPassword||!newPassword||!confirm} onClick={passwordSave}>{pwBusy?'Updating…':'Update password'}</button></div></div>}
   </div>
  </div>{toast&&<Toast message={toast} onClose={()=>setToast('')}/>} 
 </section>;
}
